### ISSUE TITLE
Vue の導入

### ISSUE THREAD

**Issue by yuta-ushijima** [yuta-ushijima/penguin-app#12]
~~• axios の導入~~ 
=> 12/10 DONE
~~• typescript の導入~~ 
=> 11/19 DONE
~~• 適当な API を叩いてデータを表示~~  
=> 12/10 DONE
~~• element-ui の導入~~ 
=> 12/10 DONE
~~• css-modules の導入~~ 
=> vueのscopedで同様の効果があるので対応不要

**Comment by mc-chinju** [comment]
css-modules の導入も
